Fix Error
[warn] there was one deprecation warning (since 2.4); re-run with -deprecation for details
[warn] one warning found
[info] Running com.example.WireTapDriver
[error] (run-main-0) java.lang.IllegalArgumentException: no matching constructor found on class com.example.MessageLogger for arguments []
java.lang.IllegalArgumentException: no matching constructor found on class com.example.MessageLogger for arguments []
	at akka.util.Reflect$.error$1(Reflect.scala:81)
	at akka.util.Reflect$.findConstructor(Reflect.scala:105)
	at akka.actor.NoArgsReflectConstructor.<init>(IndirectActorProducer.scala:103)
	at akka.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:60)
	at akka.actor.Props.producer(Props.scala:131)
	at akka.actor.Props.<init>(Props.scala:144)
	at akka.actor.Props$.apply(Props.scala:62)
	at com.example.WireTapDriver$.delayedEndpoint$com$example$WireTapDriver$1(WireTap.scala:8)
	at com.example.WireTapDriver$delayedInit$body.apply(WireTap.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.example.CompletableApp.main(CompletableApp.scala:5)
	at com.example.WireTapDriver.main(WireTap.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.